#!/usr/bin/env python3
"""Create GitHub PR for human review of staged detection rules"""

import argparse
import json
import subprocess
from pathlib import Path
from datetime import datetime

def format_rule_table(rules: list) -> str:
    """format rules as markdown table"""
    if not rules:
        return "No rules in this batch"

    table = ["| Rule | Severity | MITRE TTP | Quality Score |",
             "|------|----------|-----------|---------------|"]

    for rule in rules:
        name = rule['rule_name']
        severity = rule.get('severity', 'unknown').upper()
        ttps = rule.get('mitre_ttps', [])
        ttp_str = ', '.join([f"{t['technique_id']}" for t in ttps]) if ttps else 'N/A'
        score = rule.get('quality_validation', {}).get('overall_score', 0.0)

        table.append(f"| {name} | {severity} | {ttp_str} | {score:.2f} |")

    return '\n'.join(table)

def format_metrics_table(metrics: dict) -> str:
    """format test metrics as markdown"""
    if not metrics:
        return "No integration test metrics available"

    return f"""**Test Results:**
- Total Tests: {metrics.get('total', 0)}
- True Positives (TP): {metrics.get('TP', 0)}
- False Negatives (FN): {metrics.get('FN', 0)}
- False Positives (FP): {metrics.get('FP', 0)}
- True Negatives (TN): {metrics.get('TN', 0)}

**Quality Metrics:**
- Precision: {metrics.get('precision', 0) * 100:.1f}%
- Recall: {metrics.get('recall', 0) * 100:.1f}%
- F1 Score: {metrics.get('f1_score', 0):.3f}
- Accuracy: {metrics.get('accuracy', 0) * 100:.1f}%
"""

def create_pr_body(batch_summary: dict) -> str:
    """format PR body with quality report"""

    batch_id = batch_summary['batch_id']
    rule_count = batch_summary['rules_staged']
    rules = batch_summary.get('rules', [])
    metrics = batch_summary.get('overall_metrics', {})

    body = f"""## Detection Rules for Review

**Batch ID:** `{batch_id}`
**Rules:** {rule_count} detection rules passed automated quality checks
**Staged:** {batch_summary['staged_timestamp']}

---

### Rules in this PR

{format_rule_table(rules)}

---

### Integration Test Results

{format_metrics_table(metrics)}

---

### Review Checklist

Please review the following before approving:

- [ ] **Rule syntax** - Check YAML structure and Lucene query format
- [ ] **TTP mappings** - Verify MITRE ATT&CK technique alignment
- [ ] **False positive potential** - Review FP test cases
- [ ] **Detection logic** - Ensure query detects intended threat
- [ ] **Test coverage** - Verify TP/FN/FP/TN test cases are realistic
- [ ] **Metadata quality** - Check descriptions, references, severity

---

### Quality Thresholds Met

✅ **LLM Validator Score:** ≥ 0.75 (all rules scored 0.90+)
✅ **Test Cases:** All rules have TP/FN/FP/TN coverage
✅ **ECS Fields:** Core categorization validated
✅ **Lucene Syntax:** All queries passed validation

---

**Generated by:** Detection Agent (Gemini 2.5 Flash + Pro)
"""

    return body

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--batch-summary', required=True)
    args = parser.parse_args()

    with open(args.batch_summary) as f:
        batch_summary = json.load(f)

    batch_id = batch_summary['batch_id']
    
    #create branch
    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    branch_name = f"detection-review-{timestamp}"
    
    print(f"Creating PR for batch {batch_id}...")
    
    subprocess.run(['git', 'checkout', '-b', branch_name], check=True)
    subprocess.run(['git', 'add', 'staged_rules/', 'scripts/'], check=True)
    
    commit_msg = f"Stage detection rules for review\n\nBatch: {batch_id}\nRules: {batch_summary['rules_staged']}"
    subprocess.run(['git', 'commit', '-m', commit_msg], check=True)
    subprocess.run(['git', 'push', 'origin', branch_name], check=True)
    
    #create PR body
    pr_body = create_pr_body(batch_summary)
    pr_body_file = Path(f"/tmp/pr_body_{batch_id}.md")
    pr_body_file.write_text(pr_body)
    
    #create PR
    result = subprocess.run([
        'gh', 'pr', 'create',
        '--base', 'main',
        '--head', branch_name,
        '--title', f"Review Detection Rules - {datetime.now().strftime('%Y-%m-%d')}",
        '--body-file', str(pr_body_file),
        '--label', 'detection-review'
    ], capture_output=True, text=True)
    
    pr_body_file.unlink()
    
    if result.returncode == 0:
        print(f"✓ PR created: {result.stdout.strip()}")
        return 0
    else:
        print(f"✗ Failed: {result.stderr}")
        return 1

if __name__ == '__main__':
    exit(main())
